//Global
export const LOADINGSPINNER_UPDATED = 'LOADINGSPINNER_UPDATED';
export const FOOTER_HEIGHT_SETTED = 'FOOTER_HEIGHT_SETTED';
export const NAVBAR_HEIGHT_SETTED = 'NAVBAR_HEIGHT_SETTED';

//Auth
export const USERAUTH_LOADED = 'USERAUTH_LOADED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const AUTH_ERROR = 'AUTH_ERROR';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const EMAIL_SENT = 'EMAIL_SENT';
export const EMAIL_ERROR = 'EMAIL_ERROR';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';

//Alert
export const ALERT_REMOVED = 'ALERT_REMOVED';
export const ALERT_SETTED = 'ALERT_SETTED';

//Users
export const USER_LOADED = 'USER_LOADED';
export const USERS_LOADED = 'USERS_LOADED';
export const USER_UPDATED = 'USER_UPDATED';
export const USER_DELETED = 'USER_DELETED';
export const USERS_ERROR = 'USERS_ERROR';
export const USER_CLEARED = 'USER_CLEARED';
export const USERS_CLEARED = 'USERS_CLEARED';

//Reservations
export const RESERVATION_LOADED = 'RESERVATION_LOADED';
export const RESERVATIONS_LOADED = 'RESERVATIONS_LOADED';
export const RESERVATION_REGISTERED = 'RESERVATION_REGISTERED';
export const RESERVATION_UPDATED = 'RESERVATION_UPDATED';
export const RESERVATION_DELETED = 'RESERVATION_DELETED';
export const RESERVATION_CANCELED = 'RESERVATION_CANCELED';
export const RESERVATIONS_CLEARED = 'RESERVATIONS_CLEARED';
export const RESERVATION_CLEARED = 'RESERVATION_CLEARED';
export const RESERVATIONS_ERROR = 'RESERVATIONS_ERROR';

//JobsXReservations
export const JOBSXRESERVATIONS_LOADED = 'JOBSXRESERVATIONS_LOADED';
export const JOBSXRESERVATIONS_CLEARED = 'JOBSXRESERVATIONS_CLEARED';
export const JOBSXRESERVATIONS_ERROR = 'JOBSXRESERVATIONS_ERROR';

//Days
export const MONTHAVAILABILITY_LOADED = 'MONTHAVAILABILITY_LOADED';
export const DAYAVAILABILITY_LOADED = 'DAYAVAILABILITY_LOADED';
export const DAY_ENABLED = 'DAY_ENABLED';
export const DAY_DISABLED = 'DAY_DISABLED';
export const DAYS_DISABLED = 'DAYS_DISABLED';
export const ADD_RESERVED_DAY = 'ADD_RESERVED_DAY';
export const DELETE_RESERVED_DAY = 'DELETE_RESERVED_DAY';
export const ADD_TIME_DISABLED_DAY = 'ADD_TIME_DISABLED_DAY';
export const DELETE_TIME_DISABLED_DAY = 'DELETE_TIME_DISABLED_DAY';
export const DAYSAVAILABILITY_CLEARED = 'DAYSAVAILABILITY_CLEARED';
export const DAYSAVAILABILITY_ERROR = 'DAYSAVAILABILITY_ERROR';

//Jobs
export const JOB_LOADED = 'JOB_LOADED';
export const JOBS_LOADED = 'JOBS_LOADED';
export const JOB_REGISTERED = 'JOB_REGISTERED';
export const JOB_UPDATED = 'JOB_UPDATED';
export const JOB_DELETED = 'JOB_DELETED';
export const JOBS_ERROR = 'JOBS_ERROR';
export const JOB_DELETION_ERROR = 'JOB_DELETION_ERROR';
export const JOB_CLEARED = 'JOB_CLEARED';
export const JOBS_CLEARED = 'JOBS_CLEARED';

//Payment
export const PAYMENT_SUCCESSFUL = 'PAYMENT_SUCCESSFUL';
export const PAYMENT_STATUS_UPDATED = 'PAYMENT_STATUS_UPDATED';
export const PAYMENT_ERROR = 'PAYMENT_ERROR';
